name: Test

on:
  push:           # Triggers on push to any branch/feature
  pull_request:   # Triggers on pull requests to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # Add PYTHONPATH to allow imports from the project directory
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Check coverage
        run: |
          # Check if the coverage is at least 96%
          COVERAGE=$(coverage report --skip-covered --show-missing | grep TOTAL | awk '{print $4}' | sed 's/%//')
          if (( $(echo "$COVERAGE >= 96" | bc -l) )); then
            echo "Coverage is 96% or higher"
          else
            echo "Coverage is less than 96%. Current coverage: $COVERAGE%"
            exit 1
          fi

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: true
