name: Test

on:
  push:           # Triggers on push to any branch/feature
  pull_request:   # Triggers on pull requests to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # Add PYTHONPATH to allow imports from the project directory
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Calculate coverage
        id: coverage
        run: |
          # Fetch the coverage percentage from the report
          COVERAGE=$(coverage report | grep TOTAL | awk '{print $4}' | sed 's/%//')
          echo "Current coverage is $COVERAGE%"

          # Set the target coverage to 96%
          TARGET_COVERAGE=96

          # Check if the current coverage is at least the target coverage
          if [ $COVERAGE -ge $TARGET_COVERAGE ]; then
            echo "::set-output name=result::pass"
          else
            echo "::set-output name=result::fail"
          fi

      - name: Check coverage
        if: steps.coverage.outputs.result == 'fail'
        run: |
          echo "Coverage is less than 96%. Current coverage: ${{ steps.coverage.outputs.coverage }}%"
          exit 1
        
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: true
