name: Test

on:
  push:           # Triggers on push to any branch/feature
  pull_request:   # Triggers on pull requests to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # Add PYTHONPATH to allow imports from the project directory
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: |
          pytest --cov=./ --cov-report=xml --cov-report=term-missing --cov-fail-under=96

      - name: Check coverage
        run: |
          coverage report
          if [[ $(coverage report | grep TOTAL | awk '{print $4}' | sed 's/%//') -lt 96 ]]; then
            echo "Coverage is less than 96%"
            exit 1
          else
            echo "Coverage is 96% or higher"
          fi
